### ISSUE TITLE
kb should be written as KiB

### ISSUE THREAD

**Issue by jasonhuan** [IoBuilders/truffle-contract-size#6]
This might be an issue with truffle or solidity, but I've run into an issue where the real limit of the contracts (24576 bytes) is reached upon truffle-contract-size showing 24.0kb. 

24576 bytes = 24.0KiB (kibibytes instead of kilobits), since there's 1024 bytes in a KiB. Displaying 24.0kb implies 24000 bits, which would be 3000 bytes on almost all modern computers (8 bits in 1 byte).

**Comment by marcosio** [comment]
We have clarified the documentation and changed some parts of our code to use KiB instead of kb.
